### ISSUE TITLE
Android linting is not working with new version of arcanist

### ISSUE THREAD

**Issue by DheerendraRathor** [imobile3/cassowary#11]
After commit https://github.com/phacility/arcanist/commit/f4aadb96048b77220696ee32462458e8a23c49e9 way of linting was changed as it was looking for `$path` in `$path_map`, where `$path_map` is list of all changed files and `$path` is android's root project. 
Now since this check is failed, android lints are no longer working in arcanists.

**Comment by mbishopim3** [comment]
Hi Dheerendra, I don't believe we're seeing this locally. Do you have any `--trace` output you could share? Or perhaps submit a pull request with a proposed solution?

**Comment by DheerendraRathor** [comment]
I don't have any and neither I remember any trace output. There was no exception thrown, but there was no lint warning as well. But I created a lightweight standalone android linter using your ArcanistAndroidLint.php 
Here is my project: https://github.com/DheerendraRathor/Arcanist-Android-Lint
