### ISSUE TITLE
MobileUnitTestEngine does not detect Android tests

### ISSUE THREAD

**Issue by arriolac** [imobile3/cassowary#12]
I have 2 modules in my project. 1 module has tests that the `MobileUnitTestEngine` does not detect and run. The file structure is as follows:
- `app`
- `module_with_no_tests`
- `module_with_tests`
  - src
    - test
      - java
        - // JUnit tests

**Comment by mbishopim3** [comment]
Hello! Is your local Gradle configuration properly invoking these tests e.g. `gradle test`? Our library is entirely dependent on Gradle's invocation, not any discovery of tests itself.

**Comment by arriolac** [comment]
@mbishopim3 thanks for the response. Where should this be configured?

**Comment by mbishopim3** [comment]
We don't use JUnit internally but looks like it's a standard dependency: https://github.com/junit-team/junit/wiki/Use-with-Gradle

**Comment by arriolac** [comment]
The test configuration is specified correctly in my gradle file (as you linked). The test engine needs a way to invoke `./gradlew test` to actually run the tests though.
