### ISSUE TITLE
Configured lint engine "OCLintEngine" is not a subclass of "ArcanistLintEngine", but must be.

### ISSUE THREAD

**Issue by yishuiliunian** [imobile3/cassowary#13]
when run 
```
arc lint
```

it say : Configured lint engine "OCLintEngine" is not a subclass of "ArcanistLintEngine", but must be.

**Comment by mbishopim3** [comment]
Do you have the latest Arcanist installed and in your path? `arc upgrade` and pulling the latest here will do this.

**Comment by aelam** [comment]
@yishuiliunian  are you success on the configuration?
