### ISSUE TITLE
How can I fixed Error  (TXT5) Bad Charset issue without changing source code

### ISSUE THREAD

**Issue by aelam** [imobile3/cassowary#14]
Our source code files contains a lot of NON-ASCII  charsets. It's impossible to remove them all 
How can I update this setting let it pass?

```
   Error  (TXT5) Bad Charset
    Source code should contain only ASCII bytes with ordinal decimal values
    between 32 and 126 inclusive, plus linefeed. Do not use UTF-8 or other
    multibyte charsets.

               3 //  EMStock
               4 //
               5 //  Created by Mac mini 2012 on 14-9-26.
    >>>        6 //  Copyright (c) 2014年 flora. All rights reserved.
               7 //
               8
               9 #import "EMZnxgStockListController.h"

```

**Comment by mbishopim3** [comment]
This is actually the text linter that Phacility / Phabricator provides:

https://github.com/phacility/arcanist/blob/master/src/lint/linter/ArcanistTextLinter.php

We strongly recommend fixing the character set using some sort of tool; there's nothing built in to just skip this.
