### ISSUE TITLE
Stripping -scheme from xctool-args causes errors

### ISSUE THREAD

**Issue by paulstringer** [imobile3/cassowary#8]
Stripping the -scheme args in getXcodebuildArgs() requires the -workspace arg be removed otherwise this error occurs:

```xcodebuild: error: If you specify a workspace then you must also specify a scheme.```

In doing this though there is though another issue later when collating coverage reports. By removing these args the build location generated by running 'xctool -reporter phabricator:' and the one reported by 'xcodebuild showBuildSettings' will mismatch leading to the next error:

```ERROR 2: chdir(): No such file or directory (errno 2) at [/Volumes/Work/Benji/submodules/cassowary/libcassowary/src/unit/MobileUnitTestEngine.php:361]
arcanist(), libcassowary(), phutil()```

No files will exist in the -showBuildSettings derived directory because xctool is using -workspace and -scheme args which leads to a different build location being generated.

The steps to recreate (in our scenario) is to use the following xctool-args file with a project using the following build configurations and targets.


'''
[
  "-workspace", "App.xcworkspace",
  "-scheme", "App",
  "-sdk", "iphonesimulator",
  "-destination", "platform=iOS Simulator,name=iPad Air,OS=8.1",'
]
''


Project
  - App
Target
  - App
  - AppTests

Build Configurations
- Debug
- Test
- Release

Schemes
- App
  - Run (Debug)
  - Test (Test)
  - Profile (Release)
  - Analyze (Debug)
  - Archive (Release)

**Comment by paulstringer** [comment]
I've checked locally that leaving -scheme in place resolves these errors for me and that coverage is working.

**Comment by mbishopim3** [comment]
We have some internal use cases which we're investigating here, will let you know.

**Comment by paulstringer** [comment]
Thanks, I figured you guys had some use cases this was needed for so holding of creating any pull requests.

**Comment by mbishopim3** [comment]
Hi Paul, anything new here? Just want to check in to see if you got things to work with `HEAD` and that there are no issues. Thanks!

**Comment by paulstringer** [comment]
Unless it's been addressed in Head it's still going to be a problem for some projects. There should be a pull request with a suitable fix that I think you guys were going to see if it didn't cause any problems with your own projects.

**Comment by mbishopim3** [comment]
We are gonna put together a pull request for this, just testing now.

**Comment by paulstringer** [comment]
Thanks for checking this out.
