### ISSUE TITLE
Include into Android Project

### ISSUE THREAD

**Issue by winterDroid** [imobile3/cassowary#9]
Hello!

I think the README is outdated.
How can I get it working with my Android Project? It seems not to run ./gradlew lint..

Thanks!

**Comment by mbishopim3** [comment]
Hello! What specific issue or error message are you experiencing? If cassowary is available and you have the `MobileLintEngine` configured in your project, diffs with Android content will be handled.

**Comment by winterDroid** [comment]
Ok. But how can I run the full suit of Android checks on my local repo? If I specify like to test an activity completly and I include there for example the new Bigdecimal which should be found, it tells me no warnings...

**Comment by winterDroid** [comment]
Can you maybe explain me the setup procedure a bit more? If I run `arc linter`, I see the AndroidLinter, but I'm not able to execute it..

**Comment by jstarkeim3** [comment]
`arc linter` provides you a list of the available linters. All you have to do to execute the AndroidLinter is run the `arc lint` command.

**Comment by winterDroid** [comment]
@jstarkeim3 thanks. I tried that but for some reason it does not fine any issues that are found by `./gradlew lint`. Do you have an idea what the reason for this can be?

**Comment by mbishopim3** [comment]
Without knowing your exact project structure, if you're running `arc lint` from the base of your project, there should be a parallel `gradlew` file available there which will invoke gradle linting functions. Execution starts here:

https://github.com/imobile3/cassowary/blob/master/libcassowary/src/lint/linter/ArcanistAndroidLinter.php#L72

If that file cannot be found then `gradle` on your `PATH` will be invoked instead. You should see a `lint-results.xml` file be created temporarily.

**Comment by mbishopim3** [comment]
Appears resolved. Reopen if you need, thanks!
